[versions]
shadow = "8.1.7"
spotless = "6.25.0"
indra = "3.0.1"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
